import type { DiagnosticItem } from './types.ts';

/**
 * Banco do diagnóstico inicial: 5 áreas × 3 níveis × 2 itens. O teste é
 * adaptativo (ver engine/diagnostic.ts): cada pessoa responde 4 itens por área,
 * 20 no total, em cerca de 10 minutos. Há a opção "Não sei", sempre a última,
 * para que chutar não seja recompensado e a recomendação seja honesta.
 */
const NAO_SEI = 'Não sei';

const item = (i: Omit<DiagnosticItem, 'options'> & { options: string[] }): DiagnosticItem => ({
  ...i,
  options: [...i.options, NAO_SEI],
});

export const diagnosticItems: DiagnosticItem[] = [
  /* ---------------- Computação ---------------- */
  item({ id: 'd-comp-1a', area: 'computacao', level: 1,
    prompt: 'Qual destas peças guarda dados **mesmo com o computador desligado**?',
    options: ['Memória RAM', 'SSD ou HD', 'Registradores da CPU', 'Memória cache'], answer: 1,
    explanation: 'SSD e HD são armazenamento não volátil (non-volatile storage). RAM, cache e registradores perdem o conteúdo sem energia.' }),
  item({ id: 'd-comp-1b', area: 'computacao', level: 1,
    prompt: 'Um programa que você abre (como o navegador) é gerenciado por qual software?',
    options: ['O compilador', 'O sistema operacional', 'O BIOS do teclado', 'O roteador'], answer: 1,
    explanation: 'O sistema operacional (operating system) cria processos, divide a CPU e a memória entre eles e dá acesso a arquivos e rede.' }),
  item({ id: 'd-comp-2a', area: 'computacao', level: 2,
    prompt: 'Quanto vale o número binário `1011` em decimal?',
    options: ['9', '11', '13', '1011'], answer: 1,
    explanation: '1·8 + 0·4 + 1·2 + 1·1 = 11.' }),
  item({ id: 'd-comp-2b', area: 'computacao', level: 2,
    prompt: 'Quando você digita um endereço como `exemplo.com`, o que acontece **primeiro**?',
    options: ['O servidor envia o HTML', 'O DNS traduz o nome para um endereço IP', 'O navegador executa o JavaScript', 'O roteador criptografa a senha'], answer: 1,
    explanation: 'Antes de conectar, o navegador precisa do IP do servidor; quem resolve o nome é o DNS (Domain Name System).' }),
  item({ id: 'd-comp-3a', area: 'computacao', level: 3,
    prompt: 'Por que `0.1 + 0.2 == 0.3` é `False` na maioria das linguagens?',
    options: ['Bug do Python', '0.1 não tem representação exata em binário (ponto flutuante)', 'O operador == compara tipos, não valores', 'A soma é feita em inteiros'], answer: 1,
    explanation: 'Números como 0.1 viram dízimas em base 2; o padrão IEEE 754 arredonda, e a soma acumula o erro.' }),
  item({ id: 'd-comp-3b', area: 'computacao', level: 3,
    prompt: 'Qual a diferença entre **processo** e **thread**?',
    options: ['São sinônimos', 'Threads de um mesmo processo compartilham memória; processos têm memória isolada', 'Processos são mais leves que threads', 'Threads só existem em servidores'], answer: 1,
    explanation: 'Um processo tem seu próprio espaço de endereçamento; suas threads compartilham esse espaço, o que é rápido mas exige sincronização.' }),

  /* ---------------- Lógica ---------------- */
  item({ id: 'd-log-1a', area: 'logica', level: 1,
    prompt: 'Se "todo aluno da turma tem mochila" e "Ana é aluna da turma", então:',
    options: ['Ana tem mochila', 'Ana pode não ter mochila', 'Toda pessoa com mochila é aluna', 'Nada se pode concluir'], answer: 0,
    explanation: 'Dedução direta. Atenção: a recíproca ("todo mundo com mochila é aluno") não vale.' }),
  item({ id: 'd-log-1b', area: 'logica', level: 1,
    prompt: 'Qual o próximo número da sequência 2, 4, 8, 16, ...?',
    options: ['18', '24', '32', '64'], answer: 2,
    explanation: 'Cada termo é o dobro do anterior.' }),
  item({ id: 'd-log-2a', area: 'logica', level: 2,
    prompt: 'A expressão `(A e não B) ou B` é equivalente a:',
    options: ['A', 'B', 'A ou B', 'A e B'], answer: 2,
    explanation: 'Se B é verdadeiro, tudo é verdadeiro; se B é falso, sobra A. Isso é exatamente A ou B.' }),
  item({ id: 'd-log-2b', area: 'logica', level: 2,
    prompt: 'Você tem 8 moedas iguais e uma é mais leve. Com uma balança de dois pratos, qual o **mínimo** de pesagens para garantir que acha a leve?',
    options: ['1', '2', '3', '4'], answer: 1,
    explanation: 'Divida em 3, 3 e 2. Cada pesagem reduz as possibilidades a um terço: 8 → no máximo 3 → 1.' }),
  item({ id: 'd-log-3a', area: 'logica', level: 3,
    prompt: 'A negação de "todos os testes passaram" é:',
    options: ['Nenhum teste passou', 'Pelo menos um teste falhou', 'Todos os testes falharam', 'Alguns testes passaram'], answer: 1,
    explanation: 'não (para todo x, P(x)) ≡ existe x com não P(x).' }),
  item({ id: 'd-log-3b', area: 'logica', level: 3,
    prompt: 'Quantas comparações, no pior caso, a busca binária faz em uma lista ordenada de 1.000 itens?',
    options: ['Cerca de 10', 'Cerca de 100', 'Cerca de 500', '1.000'], answer: 0,
    explanation: 'Cada passo corta pela metade: 2¹⁰ = 1024, então cerca de 10 passos.' }),

  /* ---------------- Programação ---------------- */
  item({ id: 'd-prog-1a', area: 'programacao', level: 1,
    prompt: 'O que este código imprime?', code: 'x = 3\nx = x + 2\nprint(x)',
    options: ['3', '5', 'x + 2', 'Erro'], answer: 1,
    explanation: 'A segunda linha lê o valor atual de x (3), soma 2 e guarda 5 de volta em x.' }),
  item({ id: 'd-prog-1b', area: 'programacao', level: 1,
    prompt: 'O que este código imprime?', code: 'idade = 17\nif idade >= 18:\n    print("adulto")\nelse:\n    print("menor")',
    options: ['adulto', 'menor', 'adulto e menor', 'Nada'], answer: 1,
    explanation: '17 >= 18 é falso, então executa o bloco do else.' }),
  item({ id: 'd-prog-2a', area: 'programacao', level: 2,
    prompt: 'O que este código imprime?', code: 'total = 0\nfor i in range(1, 4):\n    total += i\nprint(total)',
    options: ['3', '6', '10', '4'], answer: 1,
    explanation: 'range(1, 4) gera 1, 2, 3 (o 4 fica de fora). 1 + 2 + 3 = 6.' }),
  item({ id: 'd-prog-2b', area: 'programacao', level: 2,
    prompt: 'O que este código imprime?', code: 'def dobro(n):\n    n * 2\n\nprint(dobro(5))',
    options: ['10', 'None', '5', 'Erro'], answer: 1,
    explanation: 'A função calcula mas não tem return; toda função sem return devolve None.' }),
  item({ id: 'd-prog-3a', area: 'programacao', level: 3,
    prompt: 'O que este código imprime?', code: 'a = [1, 2]\nb = a\nb.append(3)\nprint(a)',
    options: ['[1, 2]', '[1, 2, 3]', '[3]', 'Erro'], answer: 1,
    explanation: 'b = a não copia a lista: os dois nomes apontam para o mesmo objeto (aliasing).' }),
  item({ id: 'd-prog-3b', area: 'programacao', level: 3,
    prompt: 'O que este código imprime?', code: 'def f(n):\n    if n == 0:\n        return 0\n    return n + f(n - 1)\n\nprint(f(4))',
    options: ['4', '10', '24', 'Recursão infinita'], answer: 1,
    explanation: 'f(4) = 4 + 3 + 2 + 1 + 0 = 10. O caso base n == 0 encerra a recursão.' }),

  /* ---------------- Matemática ---------------- */
  item({ id: 'd-mat-1a', area: 'matematica', level: 1,
    prompt: 'Qual é o resto da divisão de 17 por 5?',
    options: ['2', '3', '3,4', '12'], answer: 0,
    explanation: '17 = 5·3 + 2. Em programação: 17 % 5 == 2.' }),
  item({ id: 'd-mat-1b', area: 'matematica', level: 1,
    prompt: 'Um produto de R$ 80 tem 25% de desconto. Quanto fica?',
    options: ['R$ 55', 'R$ 60', 'R$ 64', 'R$ 75'], answer: 1,
    explanation: '25% de 80 é 20; 80 − 20 = 60.' }),
  item({ id: 'd-mat-2a', area: 'matematica', level: 2,
    prompt: 'Quanto é log₂(64)?',
    options: ['5', '6', '8', '32'], answer: 1,
    explanation: '2⁶ = 64. Logaritmos aparecem sempre que algo é dividido pela metade repetidamente.' }),
  item({ id: 'd-mat-2b', area: 'matematica', level: 2,
    prompt: 'Lançando duas moedas honestas, qual a probabilidade de sair **pelo menos uma** cara?',
    options: ['1/4', '1/2', '3/4', '1'], answer: 2,
    explanation: 'O único caso sem cara é coroa-coroa (1/4). Então 1 − 1/4 = 3/4.' }),
  item({ id: 'd-mat-3a', area: 'matematica', level: 3,
    prompt: 'De quantas maneiras é possível escolher 2 pessoas de um grupo de 5 (a ordem não importa)?',
    options: ['10', '20', '25', '32'], answer: 0,
    explanation: 'C(5, 2) = 5·4 / 2 = 10.' }),
  item({ id: 'd-mat-3b', area: 'matematica', level: 3,
    prompt: 'Qual é o produto escalar dos vetores (1, 2, 3) e (4, 0, −1)?',
    options: ['1', '4', '(4, 0, −3)', '7'], answer: 0,
    explanation: '1·4 + 2·0 + 3·(−1) = 4 − 3 = 1.' }),

  /* ---------------- Inglês técnico ---------------- */
  item({ id: 'd-en-1a', area: 'ingles', level: 1,
    prompt: 'Em um programa, o botão **"Save"** serve para:',
    options: ['Apagar', 'Salvar', 'Sair', 'Pesquisar'], answer: 1,
    explanation: 'save = salvar. Outros comuns: delete (apagar), exit/quit (sair), search (pesquisar).' }),
  item({ id: 'd-en-1b', area: 'ingles', level: 1,
    prompt: 'A mensagem **"File not found"** significa:',
    options: ['Arquivo salvo', 'Arquivo não encontrado', 'Arquivo muito grande', 'Arquivo protegido'], answer: 1,
    explanation: 'file = arquivo; not found = não encontrado.' }),
  item({ id: 'd-en-2a', area: 'ingles', level: 2,
    prompt: 'Na documentação: *"This function returns None if the key is missing."* O que acontece se a chave não existir?',
    options: ['A função dá erro', 'A função devolve None', 'A função cria a chave', 'A função apaga a chave'], answer: 1,
    explanation: '"returns None" = devolve None; "missing" = ausente.' }),
  item({ id: 'd-en-2b', area: 'ingles', level: 2,
    prompt: '`TypeError: can only concatenate str (not "int") to str` indica que você tentou:',
    options: ['Dividir por zero', 'Juntar texto com número', 'Acessar um índice que não existe', 'Chamar uma função inexistente'], answer: 1,
    explanation: 'concatenate = juntar; só é possível juntar str com str, não com int.' }),
  item({ id: 'd-en-3a', area: 'ingles', level: 3,
    prompt: 'Em *"Deprecated since version 3.12; use X instead"*, o recurso:',
    options: ['Foi melhorado na 3.12', 'Está obsoleto e deve ser trocado por X', 'Só funciona na 3.12', 'É mais rápido que X'], answer: 1,
    explanation: 'deprecated = obsoleto, desaconselhado; ainda funciona, mas pode ser removido.' }),
  item({ id: 'd-en-3b', area: 'ingles', level: 3,
    prompt: 'Num code review: *"LGTM, but please address the nit about naming before merging."* O revisor:',
    options: ['Rejeitou o código', 'Aprovou, pedindo um pequeno ajuste de nomes antes do merge', 'Pediu para reescrever tudo', 'Já fez o merge'], answer: 1,
    explanation: 'LGTM = "looks good to me" (aprovado); nit = detalhe pequeno; address = tratar/resolver.' }),
];

/**
 * Regras de dispensa (placement). Conservadoras: só dispensam módulos introdutórios
 * quando a evidência é forte. O estudante sempre pode desfazer a dispensa e,
 * em qualquer caso, os cards de revisão desses módulos entram na fila.
 */
export const placementRules = [
  { moduleId: 'm0-1', requires: { computacao: 0.85 } },
  { moduleId: 'm0-2', requires: { computacao: 0.85 } },
  { moduleId: 'm0-3', requires: { computacao: 0.85 } },
  { moduleId: 'm0-4', requires: { ingles: 0.85 } },
  { moduleId: 'm1-1', requires: { logica: 0.6, programacao: 0.6 } },
  { moduleId: 'm1-2', requires: { programacao: 0.85 } },
  { moduleId: 'm1-3', requires: { programacao: 0.85, logica: 0.6 } },
  { moduleId: 'm1-4', requires: { programacao: 0.85, logica: 0.6 } },
  { moduleId: 'm1-5', requires: { programacao: 0.85, logica: 0.85 } },
  { moduleId: 'm14-1', requires: { logica: 0.85, matematica: 0.85 } },
] as const;

export const NAO_SEI_LABEL = NAO_SEI;
