import type { InterviewQuestion } from './types.ts';

/**
 * Banco de perguntas de entrevista técnica. Cada pergunta tem a versão em
 * inglês (muitas vagas fazem a entrevista em inglês), os pontos que a resposta
 * precisa cobrir (keyPoints, usados na autoavaliação) e uma resposta modelo.
 * A pessoa responde em voz alta ou por escrito ANTES de ver a resposta.
 */
const q = (x: InterviewQuestion) => x;

export const interviewQuestions: InterviewQuestion[] = [
  /* ---------- Conceitos ---------- */
  q({ id: 'iq-lista-vs-dict', category: 'conceitos', kind: 'conceitual', difficulty: 'facil',
    question: 'Quando usar uma lista e quando usar um dicionário?',
    questionEn: 'When would you use a list versus a dictionary?',
    keyPoints: ['Lista: sequência ordenada, acesso por posição', 'Dict: acesso por chave em O(1) médio', 'Busca por valor em lista é O(n)', 'Exemplo concreto de cada um'],
    answer: 'Uso lista quando a ordem importa e acesso por posição ou percorro tudo, como um histórico de mensagens. Uso dicionário quando preciso encontrar algo por uma chave, como um aluno pela matrícula: a busca é O(1) em média por causa da tabela hash, enquanto procurar em uma lista é O(n).',
    followUps: ['Por que a busca em dict é O(1) "em média" e não sempre?', 'Que tipos podem ser chave de um dict? Por quê?'] }),
  q({ id: 'iq-big-o', category: 'conceitos', kind: 'conceitual', difficulty: 'facil',
    question: 'O que significa dizer que um algoritmo é O(n²)?',
    questionEn: 'What does it mean for an algorithm to be O(n²)?',
    keyPoints: ['Cresce proporcionalmente ao quadrado da entrada', 'É limite superior assintótico', 'Constantes e termos menores são ignorados', 'Exemplo: dois laços aninhados sobre a entrada'],
    answer: 'Que o número de operações, para entradas grandes, cresce no máximo proporcionalmente a n². Dobrar a entrada multiplica o tempo por cerca de 4. É o caso típico de dois laços aninhados que comparam todos os pares. Big O descreve a tendência de crescimento, por isso ignoramos constantes e termos menores.',
    followUps: ['Como você reduziria um algoritmo O(n²) de "achar duplicatas" para O(n)?', 'O(n²) é sempre pior que O(n log n) na prática?'] }),
  q({ id: 'iq-pilha-fila', category: 'conceitos', kind: 'conceitual', difficulty: 'facil',
    question: 'Explique a diferença entre pilha e fila, com um exemplo real de cada.',
    questionEn: 'Explain the difference between a stack and a queue, with a real-world example of each.',
    keyPoints: ['Pilha: LIFO', 'Fila: FIFO', 'Pilha: desfazer (undo), pilha de chamadas', 'Fila: impressão, requisições, BFS'],
    answer: 'Pilha é LIFO: o último a entrar é o primeiro a sair, como o "desfazer" de um editor ou a pilha de chamadas de funções. Fila é FIFO: o primeiro a entrar sai primeiro, como uma fila de impressão ou de requisições em um servidor. Em Python uso list para pilha (append/pop) e collections.deque para fila, porque list.pop(0) é O(n).',
    followUps: ['Como implementar uma fila usando duas pilhas?'] }),
  q({ id: 'iq-poo-pilares', category: 'conceitos', kind: 'conceitual', difficulty: 'intermediario',
    question: 'Quando herança é uma má escolha? O que usar no lugar?',
    questionEn: 'When is inheritance a bad choice, and what would you use instead?',
    keyPoints: ['Herança só para relação "é um" verdadeira', 'Acoplamento forte com a superclasse', 'Composição: "tem um"', 'Princípio de substituição de Liskov'],
    answer: 'Herança é ruim quando a relação "é um" não é verdadeira em todos os casos, ou quando herdo só para reaproveitar código. Isso acopla a subclasse aos detalhes da superclasse e pode violar o princípio de Liskov, como o clássico Quadrado herdando de Retângulo. Nesses casos prefiro composição: o objeto tem um colaborador e delega para ele, o que é mais flexível e fácil de testar.',
    followUps: ['Dê um exemplo de violação do princípio de Liskov.'] }),
  q({ id: 'iq-processo-thread', category: 'sistemas', kind: 'conceitual', difficulty: 'intermediario',
    question: 'Qual a diferença entre processo e thread? Quando usar cada um?',
    questionEn: 'What is the difference between a process and a thread, and when would you use each?',
    keyPoints: ['Processo tem memória isolada', 'Threads compartilham memória do processo', 'Threads exigem sincronização', 'Em Python, GIL afeta CPU-bound'],
    answer: 'Um processo tem seu próprio espaço de memória; threads de um mesmo processo compartilham memória. Threads são mais leves e comunicam-se facilmente, mas precisam de sincronização para evitar condições de corrida. Processos isolam falhas. Em CPython, por causa do GIL, uso threads ou asyncio para trabalho de E/S e processos para trabalho pesado de CPU.',
    followUps: ['O que é um deadlock e quais as quatro condições para ele ocorrer?'] }),
  q({ id: 'iq-deadlock', category: 'sistemas', kind: 'conceitual', difficulty: 'avancado',
    question: 'O que é deadlock e como evitá-lo?',
    questionEn: 'What is a deadlock and how do you prevent it?',
    keyPoints: ['Espera circular por recursos', 'Condições de Coffman: exclusão mútua, posse e espera, sem preempção, espera circular', 'Ordem global de aquisição de locks', 'Timeouts'],
    answer: 'Deadlock é quando duas ou mais threads esperam umas pelas outras para sempre, cada uma segurando um recurso que a outra precisa. Ele exige as quatro condições de Coffman ao mesmo tempo; quebrar qualquer uma evita o problema. A forma mais prática é definir uma ordem global para adquirir locks, de modo que nunca haja espera circular, e usar timeouts.',
    followUps: ['Qual a diferença entre deadlock e livelock?'] }),

  /* ---------- Código ---------- */
  q({ id: 'iq-two-sum', category: 'codigo', kind: 'codigo', difficulty: 'facil',
    question: 'Dada uma lista de inteiros e um alvo, devolva os índices de dois números que somam o alvo.',
    questionEn: 'Given a list of integers and a target, return the indices of two numbers that add up to the target.',
    keyPoints: ['Solução ingênua O(n²) com dois laços', 'Solução O(n) com dict de valor → índice', 'Verificar complemento antes de inserir', 'Perguntar sobre casos sem solução e duplicatas'],
    answer: 'def dois_somam(nums, alvo):\n    vistos = {}\n    for i, x in enumerate(nums):\n        falta = alvo - x\n        if falta in vistos:\n            return vistos[falta], i\n        vistos[x] = i\n    return None\n\nUma passada só, O(n) de tempo e O(n) de memória. Verifico o complemento antes de inserir para não usar o mesmo elemento duas vezes.',
    followUps: ['E se a lista estiver ordenada? Dá para usar O(1) de memória?'] }),
  q({ id: 'iq-palindromo', category: 'codigo', kind: 'codigo', difficulty: 'facil',
    question: 'Verifique se uma frase é palíndromo, ignorando espaços, pontuação e maiúsculas.',
    questionEn: 'Check whether a sentence is a palindrome, ignoring spaces, punctuation and case.',
    keyPoints: ['Normalizar: só alfanuméricos, minúsculas', 'Comparar com o reverso ou dois ponteiros', 'Testar string vazia e um caractere', 'Mencionar acentos'],
    answer: 'def palindromo(frase):\n    s = [c.lower() for c in frase if c.isalnum()]\n    return s == s[::-1]\n\nO(n). Com dois ponteiros dá para fazer com O(1) de memória extra. Eu perguntaria se acentos contam (com unicodedata dá para removê-los).',
    followUps: ['Como fazer com dois ponteiros sem criar a lista?'] }),
  q({ id: 'iq-anagramas', category: 'codigo', kind: 'codigo', difficulty: 'intermediario',
    question: 'Agrupe uma lista de palavras em grupos de anagramas.',
    questionEn: 'Group a list of words into anagram groups.',
    keyPoints: ['Chave canônica: palavra ordenada ou contagem de letras', 'dict de chave → lista', 'Complexidade O(n·k log k)', 'defaultdict'],
    answer: 'from collections import defaultdict\n\ndef agrupar(palavras):\n    grupos = defaultdict(list)\n    for p in palavras:\n        grupos["".join(sorted(p))].append(p)\n    return list(grupos.values())\n\nA chave é a palavra com as letras ordenadas: anagramas geram a mesma chave. O(n·k log k), com k o tamanho da palavra.',
    followUps: ['Como evitar a ordenação usando contagem de letras?'] }),
  q({ id: 'iq-intervalos', category: 'codigo', kind: 'codigo', difficulty: 'intermediario',
    question: 'Dada uma lista de intervalos [início, fim], junte os que se sobrepõem.',
    questionEn: 'Given a list of intervals [start, end], merge all overlapping intervals.',
    keyPoints: ['Ordenar pelo início', 'Comparar com o último intervalo do resultado', 'O(n log n) pela ordenação', 'Casos: intervalos que se tocam, contidos'],
    answer: 'def juntar(intervalos):\n    res = []\n    for ini, fim in sorted(intervalos):\n        if res and ini <= res[-1][1]:\n            res[-1][1] = max(res[-1][1], fim)\n        else:\n            res.append([ini, fim])\n    return res\n\nOrdenando pelo início, só preciso comparar com o último intervalo já juntado.',
    followUps: ['[1,2] e [2,3] devem ser juntados? Pergunte ao entrevistador.'] }),
  q({ id: 'iq-lru', category: 'codigo', kind: 'codigo', difficulty: 'avancado',
    question: 'Implemente um cache LRU com get e put em O(1).',
    questionEn: 'Implement an LRU cache with O(1) get and put.',
    keyPoints: ['Dict para acesso O(1)', 'Lista duplamente ligada para ordem de uso', 'OrderedDict.move_to_end', 'Remover o menos usado ao exceder a capacidade'],
    answer: 'from collections import OrderedDict\n\nclass LRU:\n    def __init__(self, cap):\n        self.cap, self.d = cap, OrderedDict()\n    def get(self, k):\n        if k not in self.d:\n            return None\n        self.d.move_to_end(k)\n        return self.d[k]\n    def put(self, k, v):\n        self.d[k] = v\n        self.d.move_to_end(k)\n        if len(self.d) > self.cap:\n            self.d.popitem(last=False)\n\nPor baixo, é um dict mais uma lista duplamente ligada. Numa entrevista, explique essa estrutura mesmo usando OrderedDict.',
    followUps: ['Como implementar sem OrderedDict?', 'Como tornar thread-safe?'] }),

  /* ---------- Lógica ---------- */
  q({ id: 'iq-moedas', category: 'logica', kind: 'logica', difficulty: 'intermediario',
    question: 'Você tem 9 bolas e uma é mais pesada. Com uma balança de pratos, qual o mínimo de pesagens?',
    questionEn: 'You have 9 balls and one is heavier. Using a balance scale, what is the minimum number of weighings?',
    keyPoints: ['Dividir em três grupos', 'Cada pesagem tem 3 resultados', 'log₃(9) = 2', 'Explicar o raciocínio, não só o número'],
    answer: 'Duas. Divido em três grupos de 3 e peso dois deles: se um lado pesar mais, a bola está nele; se equilibrar, está no terceiro. Repito com as 3 bolas restantes. Cada pesagem tem três resultados possíveis, então k pesagens distinguem 3^k bolas.',
    followUps: ['E se você não souber se a bola diferente é mais leve ou mais pesada?'] }),
  q({ id: 'iq-estimativa', category: 'logica', kind: 'logica', difficulty: 'intermediario',
    question: 'Estime quanto armazenamento seria necessário para guardar todas as mensagens de texto de um app com 10 milhões de usuários por um ano.',
    questionEn: 'Estimate the storage needed to keep one year of text messages for an app with 10 million users.',
    keyPoints: ['Declarar hipóteses', 'Mensagens por usuário por dia', 'Bytes por mensagem com metadados', 'Ordem de grandeza, não precisão'],
    answer: 'Hipóteses: 10 M usuários, 40 mensagens/dia cada, 100 bytes de texto + 100 de metadados = 200 bytes. Por dia: 10⁷ × 40 × 200 = 8 × 10¹⁰ bytes, cerca de 80 GB. Por ano: cerca de 29 TB, antes de replicação (×3, quase 90 TB). O importante é deixar as hipóteses explícitas e saber ajustá-las.',
    followUps: ['E se 10% das mensagens tiverem uma imagem de 200 KB?'] }),

  /* ---------- Git ---------- */
  q({ id: 'iq-merge-rebase', category: 'git', kind: 'conceitual', difficulty: 'intermediario',
    question: 'Qual a diferença entre merge e rebase? Quando você não deve fazer rebase?',
    questionEn: 'What is the difference between merge and rebase, and when should you avoid rebasing?',
    keyPoints: ['Merge cria commit de junção e preserva histórico', 'Rebase reescreve commits sobre nova base', 'Histórico linear', 'Nunca rebase em branch compartilhada já publicada'],
    answer: 'Merge junta duas linhas de história criando um commit de merge, sem alterar commits existentes. Rebase reaplica meus commits sobre outra base, criando commits novos e um histórico linear. Como reescreve a história, não faço rebase de commits que outras pessoas já baixaram: elas ficariam com um histórico divergente.',
    followUps: ['Como você desfaria um commit que já está na main?'] }),
  q({ id: 'iq-conflito', category: 'git', kind: 'conceitual', difficulty: 'facil',
    question: 'O que é um conflito de merge e como você resolve?',
    questionEn: 'What is a merge conflict and how do you resolve it?',
    keyPoints: ['Mesmas linhas alteradas nos dois lados', 'Marcadores <<<<<<< ======= >>>>>>>', 'Entender a intenção dos dois lados', 'Rodar os testes depois'],
    answer: 'Acontece quando os dois lados mudaram as mesmas linhas e o Git não sabe qual manter. Ele marca o trecho com <<<<<<<, ======= e >>>>>>>. Eu leio as duas versões, entendo a intenção de cada uma, escrevo a versão correta (às vezes uma combinação), removo os marcadores, rodo os testes e faço o commit.',
    followUps: ['Como diminuir a chance de conflitos em equipe?'] }),

  /* ---------- Banco de dados ---------- */
  q({ id: 'iq-indice', category: 'banco-de-dados', kind: 'conceitual', difficulty: 'intermediario',
    question: 'O que é um índice em banco de dados? Por que não indexar todas as colunas?',
    questionEn: 'What is a database index, and why not index every column?',
    keyPoints: ['Estrutura auxiliar (B-tree) para busca rápida', 'Busca O(log n) em vez de varredura', 'Custo em escrita e espaço', 'Indexar colunas de WHERE/JOIN frequentes'],
    answer: 'Um índice é uma estrutura auxiliar, geralmente uma B-tree, que permite achar linhas por uma coluna sem ler a tabela inteira, como o índice remissivo de um livro. Não indexo tudo porque cada índice ocupa espaço e precisa ser atualizado a cada INSERT, UPDATE e DELETE, deixando escritas mais lentas. Indexo colunas usadas em filtros e JOINs frequentes e confirmo com EXPLAIN.',
    followUps: ['Um índice em (a, b) ajuda uma consulta que filtra só por b?'] }),
  q({ id: 'iq-acid', category: 'banco-de-dados', kind: 'conceitual', difficulty: 'intermediario',
    question: 'O que significa ACID?',
    questionEn: 'What does ACID stand for?',
    keyPoints: ['Atomicidade', 'Consistência', 'Isolamento', 'Durabilidade', 'Exemplo de transferência bancária'],
    answer: 'Atomicity: a transação acontece por inteiro ou não acontece. Consistency: leva o banco de um estado válido para outro, respeitando restrições. Isolation: transações simultâneas não veem estados intermediários umas das outras (em graus configuráveis). Durability: o que foi confirmado sobrevive a quedas. Exemplo: numa transferência, debitar e creditar precisam acontecer juntos.',
    followUps: ['O que é uma leitura suja (dirty read)?'] }),
  q({ id: 'iq-sql-segundo-maior', category: 'banco-de-dados', kind: 'codigo', difficulty: 'intermediario',
    question: 'Escreva uma consulta SQL que encontre o segundo maior salário da tabela funcionarios.',
    questionEn: 'Write a SQL query to find the second highest salary in the employees table.',
    keyPoints: ['DISTINCT para empates', 'ORDER BY ... DESC LIMIT 1 OFFSET 1', 'Alternativa com subconsulta MAX', 'Caso sem segundo salário'],
    answer: 'SELECT DISTINCT salario FROM funcionarios ORDER BY salario DESC LIMIT 1 OFFSET 1;\n\nOu: SELECT MAX(salario) FROM funcionarios WHERE salario < (SELECT MAX(salario) FROM funcionarios);\n\nA segunda forma devolve NULL quando não existe segundo salário, o que costuma ser o comportamento desejado.',
    followUps: ['E o N-ésimo maior? Conhece funções de janela (DENSE_RANK)?'] }),

  /* ---------- Redes e web ---------- */
  q({ id: 'iq-url', category: 'redes', kind: 'conceitual', difficulty: 'intermediario',
    question: 'O que acontece quando você digita uma URL no navegador e aperta Enter?',
    questionEn: 'What happens when you type a URL into the browser and press Enter?',
    keyPoints: ['Resolução DNS', 'Conexão TCP (e TLS)', 'Requisição HTTP', 'Resposta e renderização (HTML, CSS, JS)', 'Cache em várias camadas'],
    answer: 'O navegador interpreta a URL e resolve o nome via DNS (com caches no caminho). Abre uma conexão TCP com o IP, faz o handshake TLS se for HTTPS, e envia a requisição HTTP. O servidor responde com status, cabeçalhos e corpo. O navegador monta o DOM a partir do HTML, baixa CSS, JS e imagens, aplica estilos, calcula o layout e pinta a tela.',
    followUps: ['Onde pode haver cache nesse caminho?', 'O que muda com HTTP/3?'] }),
  q({ id: 'iq-tcp-udp', category: 'redes', kind: 'conceitual', difficulty: 'facil',
    question: 'Qual a diferença entre TCP e UDP? Dê um uso para cada.',
    questionEn: 'What is the difference between TCP and UDP? Give a use case for each.',
    keyPoints: ['TCP: orientado a conexão, confiável, ordenado', 'UDP: sem conexão, sem garantia, menor latência', 'TCP: web, e-mail', 'UDP: DNS, jogos, voz'],
    answer: 'TCP estabelece conexão e garante entrega, ordem e controle de congestionamento, ao custo de latência. UDP só envia datagramas, sem garantias, mas é leve e rápido. Uso TCP para páginas web e APIs, onde nenhum byte pode faltar, e UDP para chamadas de voz ou jogos, onde um pacote atrasado já não serve.',
    followUps: ['Como o QUIC entrega confiabilidade em cima de UDP?'] }),
  q({ id: 'iq-rest', category: 'web', kind: 'conceitual', difficulty: 'facil',
    question: 'Qual a diferença entre PUT, PATCH e POST?',
    questionEn: 'What is the difference between PUT, PATCH and POST?',
    keyPoints: ['POST cria / ação não idempotente', 'PUT substitui o recurso, idempotente', 'PATCH altera parcialmente', 'Idempotência explicada'],
    answer: 'POST geralmente cria um recurso novo e não é idempotente: repetir cria duplicatas. PUT substitui o recurso inteiro naquele endereço e é idempotente: repetir dá o mesmo resultado. PATCH aplica uma alteração parcial. Idempotência importa porque clientes e proxies podem repetir requisições quando a rede falha.',
    followUps: ['Que status você devolve ao criar um recurso? E ao apagar?'] }),
  q({ id: 'iq-xss-csrf', category: 'web', kind: 'conceitual', difficulty: 'avancado',
    question: 'Explique XSS e CSRF e como se defender de cada um.',
    questionEn: 'Explain XSS and CSRF and how to defend against each.',
    keyPoints: ['XSS: injetar script que roda no navegador da vítima', 'Defesa XSS: escapar saída, CSP, não usar innerHTML com dados', 'CSRF: site malicioso faz o navegador enviar requisição autenticada', 'Defesa CSRF: SameSite, token anti-CSRF'],
    answer: 'XSS é quando dados de usuário viram código executado no navegador de outra pessoa; defendo escapando a saída conforme o contexto, evitando innerHTML com dados e usando Content-Security-Policy. CSRF é quando outro site faz o navegador da vítima enviar uma requisição com os cookies dela; defendo com cookies SameSite, tokens anti-CSRF e exigindo métodos não-GET para alterações.',
    followUps: ['Por que um cookie HttpOnly ajuda contra XSS, mas não resolve?'] }),
  q({ id: 'iq-senhas', category: 'web', kind: 'conceitual', difficulty: 'intermediario',
    question: 'Como você armazenaria senhas de usuários?',
    questionEn: 'How would you store user passwords?',
    keyPoints: ['Nunca em texto puro nem com criptografia reversível', 'Hash lento com sal: Argon2id, scrypt, bcrypt', 'Sal único por usuário', 'Comparação em tempo constante'],
    answer: 'Nunca em texto puro e nunca com criptografia reversível. Uso uma função de hash de senha lenta e com sal único por usuário, como Argon2id, scrypt ou bcrypt, com parâmetros de custo ajustados. Hashes rápidos como SHA-256 são inadequados porque permitem bilhões de tentativas por segundo. Na verificação, comparo em tempo constante.',
    followUps: ['O que é um ataque de credential stuffing e como mitigá-lo?'] }),

  /* ---------- Design de sistemas ---------- */
  q({ id: 'iq-encurtador', category: 'design', kind: 'conceitual', difficulty: 'avancado',
    question: 'Projete um encurtador de URLs.',
    questionEn: 'Design a URL shortener.',
    keyPoints: ['Requisitos e escala antes de desenhar', 'Geração do código: contador + base62 ou hash', 'Banco chave-valor, leitura muito maior que escrita', 'Cache e redirecionamento 301/302', 'Colisões, expiração, abuso'],
    answer: 'Começo pelos requisitos: criar link curto, redirecionar, talvez estatísticas; volume de leitura muito maior que de escrita. Gero o código com um contador distribuído convertido para base62 (7 caracteres dão cerca de 3,5 trilhões de combinações). Guardo código → URL em um banco chave-valor, com cache na frente para os links populares. O redirecionamento usa 302 se eu quiser contar acessos. Trato abuso com rate limit e verificação de URLs maliciosas.',
    followUps: ['Como você contaria cliques sem deixar o redirecionamento lento?'] }),
  q({ id: 'iq-escala', category: 'design', kind: 'conceitual', difficulty: 'avancado',
    question: 'Seu serviço está lento sob carga. Como você investiga?',
    questionEn: 'Your service is slow under load. How do you investigate?',
    keyPoints: ['Medir antes de mudar', 'Métricas: latência p50/p99, erros, saturação', 'Encontrar o gargalo (CPU, banco, rede, locks)', 'Hipótese, mudança, nova medição'],
    answer: 'Primeiro meço: latência por percentil, taxa de erros e uso de recursos (os "golden signals"). Comparo com o normal e localizo o componente saturado: CPU, banco (consultas lentas, falta de índice), conexões, locks ou uma dependência externa. Formulo uma hipótese, faço uma mudança por vez e meço de novo. Só depois considero escalar horizontalmente ou adicionar cache.',
    followUps: ['Por que olhar p99 e não só a média?'] }),

  /* ---------- Comportamental ---------- */
  q({ id: 'iq-bug-dificil', category: 'comportamental', kind: 'comportamental', difficulty: 'intermediario',
    question: 'Conte sobre um bug difícil que você resolveu.',
    questionEn: 'Tell me about a difficult bug you solved.',
    keyPoints: ['Estrutura STAR: situação, tarefa, ação, resultado', 'Processo de investigação, não só a solução', 'O que aprendeu', 'O que mudou para evitar de novo'],
    answer: 'Use STAR. Situação: contexto curto do projeto. Tarefa: qual era o sintoma e o impacto. Ação: como você reproduziu, que hipóteses testou, que ferramentas usou (logs, depurador, bisect). Resultado: a causa real, a correção e o teste que impede a volta do bug. Feche com o que aprendeu. Prefira um exemplo de um projeto da trilha que você conheça a fundo.',
    followUps: ['O que você faria diferente hoje?'] }),
  q({ id: 'iq-discordancia', category: 'comportamental', kind: 'comportamental', difficulty: 'intermediario',
    question: 'Conte sobre uma vez em que você discordou de alguém da equipe.',
    questionEn: 'Tell me about a time you disagreed with a teammate.',
    keyPoints: ['Respeito e foco no problema, não na pessoa', 'Dados e argumentos', 'Disposição para estar errado', 'Resultado e relação preservada'],
    answer: 'Mostre que você discorda com argumentos e dados, ouve o outro lado e aceita a decisão do grupo. Um bom exemplo descreve a divergência (por exemplo, sobre uma escolha técnica), como vocês testaram as alternativas e qual foi o resultado. Evite histórias em que você "venceu" e o colega "perdeu".',
    followUps: ['E se a decisão final tivesse sido contra a sua opinião?'] }),
  q({ id: 'iq-sem-saber', category: 'comportamental', kind: 'comportamental', difficulty: 'facil',
    question: 'O que você faz quando não sabe a resposta de uma pergunta técnica na entrevista?',
    questionEn: 'What do you do when you do not know the answer to a technical question?',
    keyPoints: ['Admitir com honestidade', 'Raciocinar em voz alta a partir do que sabe', 'Fazer perguntas de esclarecimento', 'Dizer como descobriria'],
    answer: 'Digo que não sei com certeza, raciocino em voz alta a partir do que sei, faço perguntas de esclarecimento e explico como eu verificaria (documentação, um experimento pequeno). Entrevistadores avaliam o raciocínio e a honestidade; inventar é pior do que admitir.',
    followUps: [] }),
];

export interface CareerSection {
  id: string;
  title: string;
  titleEn: string;
  intro: string;
  items: Array<{ title: string; body: string }>;
}

/** Guia de carreira: o que construir, como mostrar e como se preparar. */
export const careerGuide: CareerSection[] = [
  {
    id: 'curriculo',
    title: 'Currículo',
    titleEn: 'Résumé / CV',
    intro: 'Um currículo de tecnologia é lido em menos de um minuto. Ele precisa mostrar, rapidamente, o que você construiu e com quais ferramentas.',
    items: [
      { title: 'Uma página', body: 'No início da carreira, uma página basta. Ordem: contato (e-mail, GitHub, LinkedIn, portfólio), resumo de 2 linhas, projetos, experiência, formação, habilidades.' },
      { title: 'Projetos com resultado', body: 'Para cada projeto: o que é, a tecnologia e um resultado verificável. Ruim: "Fiz uma API". Bom: "API REST de tarefas em Python com autenticação, 40 testes automatizados e CI no GitHub Actions".' },
      { title: 'Verbos de ação', body: 'Comece cada linha com um verbo: construí, automatizei, reduzi, testei, documentei. Em inglês: built, automated, reduced, tested, documented.' },
      { title: 'Sem exagero', body: 'Liste só tecnologias sobre as quais você aguenta 10 minutos de perguntas. "Noções de" é melhor que mentir.' },
      { title: 'Versão em inglês', body: 'Mantenha uma versão em inglês. Vagas remotas e muitas empresas no Brasil pedem.' },
    ],
  },
  {
    id: 'github',
    title: 'GitHub',
    titleEn: 'GitHub profile',
    intro: 'Para quem está começando, o GitHub é a prova de que você programa. Recrutadores olham o perfil e abrem um ou dois repositórios.',
    items: [
      { title: 'README de perfil', body: 'Crie um repositório com o seu nome de usuário: o README dele aparece no topo do perfil. Diga quem você é, o que estuda e fixe seus 4–6 melhores projetos.' },
      { title: 'README de cada projeto', body: 'O que é, por que existe, imagem ou GIF, como rodar (passo a passo), como testar, decisões técnicas e próximos passos.' },
      { title: 'Histórico de commits', body: 'Commits pequenos com mensagens claras mostram como você trabalha. Evite um único commit "projeto pronto".' },
      { title: 'Testes e CI', body: 'Um badge verde de CI e uma pasta de testes diferenciam você da maioria dos portfólios de iniciante.' },
      { title: 'Contribuição open source', body: 'Uma contribuição aceita em um projeto real (Projeto 10) vale mais do que cinco tutoriais copiados.' },
    ],
  },
  {
    id: 'portfolio',
    title: 'Portfólio',
    titleEn: 'Portfolio',
    intro: 'O portfólio conta a história por trás do código: que problema você resolveu e como pensou.',
    items: [
      { title: 'Estudos de caso', body: 'Para 2–3 projetos, escreva uma página: problema, restrições, alternativas consideradas, decisão, resultado e o que faria diferente.' },
      { title: 'Projetos com usuário real', body: 'Um sistema que alguém de verdade usa (Projeto 9) é o item mais forte de um portfólio júnior.' },
      { title: 'Qualidade acima de quantidade', body: 'Três projetos completos, testados e publicados valem mais que quinze pela metade.' },
    ],
  },
  {
    id: 'entrevistas',
    title: 'Como se preparar para entrevistas',
    titleEn: 'Interview preparation',
    intro: 'Entrevistas técnicas costumam ter etapas: triagem, exercício de código (ao vivo ou para casa), conversa técnica e conversa comportamental.',
    items: [
      { title: 'Pense em voz alta', body: 'Em problemas de código: repita o problema com suas palavras, pergunte sobre casos limite, proponha a solução simples, analise a complexidade, melhore, escreva e teste com um exemplo.' },
      { title: 'Pratique com tempo', body: 'Use o modo "simulado" desta área: 25 minutos por pergunta, respondendo antes de ver a resposta modelo, e marque os pontos-chave que cobriu.' },
      { title: 'Histórias STAR', body: 'Prepare 5 histórias (bug difícil, conflito, erro que cometeu, algo que aprendeu sozinho, entrega sob pressão) no formato situação, tarefa, ação, resultado.' },
      { title: 'Entrevistas em inglês', body: 'Treine responder em voz alta as versões em inglês das perguntas. Use as frases úteis: "Let me make sure I understand the problem", "Can I assume the input is sorted?", "The time complexity is O(n) because...".' },
      { title: 'Pergunte também', body: 'Ao final, faça perguntas: como é o processo de revisão de código, como a equipe lida com incidentes, como é o primeiro mês de uma pessoa júnior.' },
    ],
  },
  {
    id: 'caminhos',
    title: 'Caminhos de carreira',
    titleEn: 'Career paths',
    intro: 'A trilha cobre a base comum. Depois dela, você aprofunda em uma direção. Os níveis indicados são onde está o núcleo de cada caminho.',
    items: [
      { title: 'Back-end', body: 'Níveis 6 (HTTP, APIs), 7 (bancos), 9 (redes), 11 (segurança) e 12 (deploy). Projetos 3, 5, 8 e 9.' },
      { title: 'Front-end', body: 'Nível 6 em profundidade, acessibilidade (WCAG), desempenho web. Projetos 4 e 9.' },
      { title: 'Dados e IA', body: 'Níveis 7, 13 e 14. Projeto 7, e mais estatística e engenharia de dados.' },
      { title: 'Infraestrutura, DevOps e SRE', body: 'Níveis 8, 9 e 12. Projetos 5 (parte de containers), 8 e 9.' },
      { title: 'Segurança', body: 'Níveis 8, 9 e 11. Comece por CTFs educacionais e pelo OWASP.' },
    ],
  },
];
