import type { Project } from './types.ts';
import { t } from './helpers.ts';

/**
 * Sequência de projetos. Cada projeto cresce ao longo de vários módulos (as
 * lições têm etapas "Projeto" que apontam para cá). A ideia é terminar a trilha
 * com um portfólio de 10 repositórios de dificuldade crescente, cada um com
 * README, testes e histórico de commits que mostram evolução.
 */
export const projects: Project[] = [
  {
    id: 'p1-calculadora',
    order: 1,
    title: 'Calculadora no terminal',
    titleEn: 'Command-line calculator',
    tier: 'iniciante',
    summary: 'Seu primeiro programa completo: lê números e uma operação, calcula, trata divisão por zero e repete até o usuário sair.',
    requires: ['m1-2'],
    skills: ['logica-variaveis', 'logica-entrada-saida', 'prog-condicionais', 'prog-loops', 'prog-funcoes'],
    requirements: [
      'Ler dois números e uma operação (+, -, *, /, //, %, **) com input().',
      'Converter a entrada para número e avisar quando ela não for numérica.',
      'Tratar divisão por zero com uma mensagem clara, sem o programa quebrar.',
      'Repetir até o usuário digitar "sair".',
      'Organizar o cálculo em funções: somar, subtrair, multiplicar, dividir e calcular(a, op, b).',
    ],
    milestones: [
      { title: 'Parte 1: operações fixas', details: 'Variáveis com valores fixos e print das quatro operações (Nível 1, Variáveis).' },
      { title: 'Parte 2: mais operadores', details: 'Divisão inteira, resto e potência. Observe o ZeroDivisionError.' },
      { title: 'Parte 3: entrada do usuário', details: 'input() + float(); o que acontece com "abc"?' },
      { title: 'Parte 4: escolher a operação', details: 'if/elif/else e mensagem para operação desconhecida.' },
      { title: 'Parte 5: laço', details: 'while até "sair".' },
      { title: 'Final: funções', details: 'calcular(a, op, b) devolve o resultado; o programa principal só faz entrada e saída.' },
    ],
    acceptance: [
      'calcular(6, "/", 3) devolve 2.0 e calcular(7, "//", 2) devolve 3.',
      'Dividir por zero mostra uma mensagem e o programa continua.',
      'Digitar texto no lugar de número não derruba o programa.',
      'Nenhuma função imprime e calcula ao mesmo tempo (separação entre lógica e E/S).',
    ],
    stretch: ['Histórico das últimas 5 contas.', 'Aceitar a expressão inteira em uma linha, como "3 * 4".', 'Escrever 5 testes com assert para calcular().'],
    english: [
      t('entrada do usuário', 'user input', 'Dados digitados por quem usa o programa.'),
      t('divisão por zero', 'division by zero', 'Operação indefinida; em Python gera ZeroDivisionError.'),
      t('laço principal', 'main loop', 'Repetição que mantém um programa interativo funcionando.'),
    ],
  },
  {
    id: 'p2-todo',
    order: 2,
    title: 'Lista de tarefas com arquivo e testes',
    titleEn: 'To-do list with persistence and tests',
    tier: 'iniciante',
    summary: 'Uma lista de tarefas de terminal que salva em JSON, trata entrada inválida e é dividida em módulos testados com pytest.',
    requires: ['m1-5', 'm2-2'],
    skills: ['prog-listas', 'prog-dicionarios', 'prog-arquivos', 'py-excecoes', 'py-modulos', 'py-testes'],
    requirements: [
      'Adicionar, listar (numerado), concluir e remover tarefas.',
      'Cada tarefa é um dict com titulo, feita e prioridade.',
      'Salvar em tarefas.json ao sair e carregar ao abrir.',
      'Tratar arquivo inexistente, JSON corrompido e número de tarefa inválido.',
      'Separar em modelo.py, armazenamento.py e main.py.',
      'Testes com pytest cobrindo todas as regras de modelo.py.',
    ],
    milestones: [
      { title: 'Parte 1: lista de strings', details: 'Adicionar, listar com enumerate, remover.' },
      { title: 'Parte 2: dicionários', details: 'Tarefas com prioridade e status.' },
      { title: 'Parte 3: arquivo JSON', details: 'json.dump/json.load com with open().' },
      { title: 'Parte 4: robustez', details: 'try/except específicos, nunca except genérico.' },
      { title: 'Parte 5: módulos e venv', details: 'Estrutura profissional no seu computador.' },
      { title: 'Final: testes', details: 'pytest com casos válidos e inválidos.' },
    ],
    acceptance: [
      'Fechar e abrir o programa preserva as tarefas.',
      'Apagar ou corromper tarefas.json não derruba o programa.',
      'pytest passa com pelo menos 8 testes.',
      'main.py não contém regra de negócio, só interação.',
    ],
    stretch: ['Datas de vencimento com datetime.', 'Filtro por texto.', 'Interface de linha de comando com argparse (tarefas add "comprar pão").'],
    english: [
      t('persistência', 'persistence', 'Guardar dados para além da execução do programa.'),
      t('caso de teste', 'test case', 'Uma situação com entrada e resultado esperado.'),
      t('caso limite', 'edge case', 'Entrada nos extremos: lista vazia, número 0, texto enorme.'),
    ],
  },
  {
    id: 'p3-cadastro',
    order: 3,
    title: 'Sistema de cadastro acadêmico',
    titleEn: 'Student records system',
    tier: 'intermediario',
    summary: 'Cadastro de alunos que evolui de dict em memória para objetos, camadas, SQLite com relacionamentos, índices e transações.',
    requires: ['m3-3'],
    skills: ['ed-hash', 'alg-busca', 'poo-classes', 'poo-heranca', 'bd-sql', 'bd-joins', 'bd-modelagem'],
    requirements: [
      'Buscar aluno por matrícula em O(1) e por nome (parcial, sem diferenciar maiúsculas).',
      'Modelar Aluno, Professor e Disciplina com classes; Cadastro encapsula o armazenamento.',
      'Exportar para CSV e JSON via interface Exportador (composição).',
      'Persistir em SQLite com consultas parametrizadas.',
      'Matrículas N:N e boletim do aluno com JOIN.',
      'Esquema na 3FN, índices justificados e matrícula múltipla em uma transação.',
    ],
    milestones: [
      { title: 'Parte 1: estruturas de dados', details: 'dict de matrícula → aluno; relatórios por curso.' },
      { title: 'Parte 2: classes', details: 'dataclass Aluno e classe Cadastro.' },
      { title: 'Parte 3: herança e composição', details: 'Pessoa → Aluno/Professor; Exportador CSV/JSON.' },
      { title: 'Parte 4: SQLite', details: 'Trocar só a camada de armazenamento.' },
      { title: 'Parte 5: relacionamentos', details: 'Disciplinas, matrículas e boletim.' },
      { title: 'Parte 6: modelagem e desempenho', details: '3FN, EXPLAIN QUERY PLAN, transação.' },
    ],
    acceptance: [
      'Trocar JSON por SQLite não muda nenhuma linha fora do módulo de armazenamento.',
      'Nenhuma consulta monta SQL com f-string ou concatenação.',
      'Uma matrícula que falha no meio não deixa dados parciais (rollback).',
      'Testes usam banco :memory: e rodam em menos de 1 segundo.',
    ],
    stretch: ['Importação de CSV com relatório de linhas rejeitadas.', 'Migrações versionadas do esquema.', 'Interface web simples (depois do Nível 6).'],
    english: [
      t('camada de acesso a dados', 'data access layer', 'Parte do código que conversa com o banco; o resto não sabe qual banco é.'),
      t('consulta parametrizada', 'parameterized query', 'SQL com marcadores (?) preenchidos pelo driver, que impede SQL injection.'),
      t('reverter', 'rollback', 'Desfazer todas as operações de uma transação.'),
    ],
  },
  {
    id: 'p4-portfolio',
    order: 4,
    title: 'Portfólio pessoal acessível',
    titleEn: 'Accessible personal portfolio',
    tier: 'intermediario',
    summary: 'Seu site pessoal em HTML, CSS e JavaScript puros, acessível, responsivo, publicado, e o seu GitHub organizado como vitrine.',
    requires: ['m6-1'],
    skills: ['web-html-css', 'web-javascript', 'tools-git'],
    requirements: [
      'HTML semântico (header, main, nav, section, footer) com hierarquia de títulos correta.',
      'Layout responsivo com Grid/Flexbox, sem framework.',
      'Tema claro/escuro lembrado com localStorage e respeitando prefers-color-scheme.',
      'Filtro de projetos por tecnologia e formulário com validação acessível.',
      'Publicado (GitHub Pages ou similar) com domínio HTTPS.',
      'Cada projeto da trilha em um repositório com README, licença e .gitignore.',
    ],
    milestones: [
      { title: 'Parte 1: estrutura e estilo', details: 'Semântica, contraste, foco visível.' },
      { title: 'Parte 2: interatividade', details: 'Tema, filtro e formulário com aria-describedby.' },
      { title: 'Parte 3: GitHub como vitrine', details: 'Repositórios, READMEs, PRs e GitHub Pages.' },
    ],
    acceptance: [
      'Navegável 100% por teclado, com foco sempre visível.',
      'Lighthouse: Acessibilidade 100, Desempenho ≥ 90.',
      'Sem erros no validador do W3C.',
      'Funciona em tela de 320 px sem rolagem horizontal.',
    ],
    stretch: ['Página de cada projeto com estudo de caso (problema, decisões, resultado).', 'Versão em inglês do site.'],
    english: [
      t('acessibilidade', 'accessibility (a11y)', 'Garantir que pessoas com deficiência consigam usar o site.'),
      t('responsivo', 'responsive', 'Que se adapta a telas de tamanhos diferentes.'),
      t('implantar/publicar', 'deploy', 'Colocar o site no ar.'),
    ],
  },
  {
    id: 'p5-api',
    order: 5,
    title: 'API REST de tarefas, segura e containerizada',
    titleEn: 'Secure, containerized REST API',
    tier: 'avancado',
    summary: 'Uma API de back-end completa: CRUD, validação, testes, CI, autenticação, auditoria OWASP, Docker e PostgreSQL.',
    requires: ['m6-3'],
    skills: ['web-http-api', 'eng-testes-ci', 'seg-fundamentos', 'seg-web', 'devops-containers'],
    requirements: [
      'CRUD de tarefas com códigos de status corretos (201, 204, 400, 404, 409).',
      'Validação de entrada com mensagens de erro consistentes (JSON).',
      'Documentação OpenAPI gerada ou escrita.',
      'Testes de unidade e de integração; CI no GitHub Actions.',
      'Cadastro e login com hash de senha (Argon2id/bcrypt) e cookie HttpOnly; Secure; SameSite.',
      'Cada usuário só vê as próprias tarefas (sem BOLA).',
      'Dockerfile multi-stage (usuário não-root) e compose.yaml com PostgreSQL.',
    ],
    milestones: [
      { title: 'Parte 1: CRUD', details: 'Rotas, validação, status, OpenAPI.' },
      { title: 'Parte 2: CI', details: 'Lint e testes em cada push; badge no README.' },
      { title: 'Parte 3: autenticação', details: 'Senhas, sessão, rate limit no login.' },
      { title: 'Parte 4: auditoria', details: 'Checklist OWASP com evidência de teste para cada item.' },
      { title: 'Parte 5: containers', details: 'Imagem pequena, compose com banco, CI constrói a imagem.' },
    ],
    acceptance: [
      'Teste automatizado prova que o usuário A recebe 404 ao acessar a tarefa do usuário B.',
      'Tentativas de SQL injection nos campos não alteram o banco (teste).',
      'docker compose up sobe API e banco do zero.',
      'Nenhum segredo no repositório (variáveis de ambiente).',
    ],
    stretch: ['Paginação com cursor.', 'Logs estruturados e endpoint /health.', 'Deploy em um provedor de nuvem com HTTPS.'],
    english: [
      t('ponto de extremidade', 'endpoint', 'Uma rota da API: método + caminho.'),
      t('limitação de taxa', 'rate limiting', 'Restringir quantas requisições um cliente pode fazer em um período.'),
      t('autorização quebrada em nível de objeto', 'broken object level authorization (BOLA)', 'Falha em verificar se o usuário pode acessar aquele registro específico.'),
    ],
  },
  {
    id: 'p6-rotas',
    order: 6,
    title: 'Planejador de rotas',
    titleEn: 'Route planner',
    tier: 'avancado',
    summary: 'Lê um mapa de cidades e estradas, encontra o menor caminho e compara algoritmos com medições reais.',
    requires: ['m4-6'],
    skills: ['ed-grafos', 'alg-grafos', 'alg-complexidade', 'ed-arvores'],
    requirements: [
      'Carregar um grafo ponderado de um CSV (origem, destino, distância).',
      'BFS para menor número de trechos e Dijkstra (com heapq) para menor distância.',
      'Reconstruir e mostrar o caminho, não só o custo.',
      'Detectar cidades inalcançáveis e entrada inválida (peso negativo).',
      'Medir tempo de execução em grafos de 100, 1.000 e 10.000 vértices e comparar com a análise Big O.',
    ],
    milestones: [
      { title: 'Modelagem', details: 'Lista de adjacência com dict de listas.' },
      { title: 'Algoritmos', details: 'BFS e Dijkstra com testes em grafos pequenos feitos à mão.' },
      { title: 'Medição', details: 'Gerador de grafos aleatórios e gráfico de tempo × tamanho.' },
    ],
    acceptance: [
      'Resultados de Dijkstra batem com uma implementação de força bruta em 100 grafos aleatórios pequenos (teste de propriedade).',
      'O README explica por que Dijkstra não funciona com pesos negativos.',
    ],
    stretch: ['A* com heurística de distância em linha reta.', 'Bellman-Ford para pesos negativos.', 'Visualização do caminho em SVG.'],
    english: [
      t('menor caminho', 'shortest path', 'Caminho de custo total mínimo entre dois vértices.'),
      t('fila de prioridade', 'priority queue', 'Estrutura que sempre entrega o menor (ou maior) elemento primeiro.'),
      t('teste baseado em propriedades', 'property-based testing', 'Testar uma regra geral com muitas entradas geradas.'),
    ],
  },
  {
    id: 'p7-ml',
    order: 7,
    title: 'Classificador do zero',
    titleEn: 'Classifier from scratch',
    tier: 'avancado',
    summary: 'Implementa k-NN, regressão logística e uma rede neural pequena do zero, compara com bibliotecas e escreve um relatório honesto.',
    requires: ['m13-1'],
    skills: ['ia-ml', 'ia-redes-neurais', 'mat-probabilidade'],
    requirements: [
      'Separar treino, validação e teste sem vazamento de dados.',
      'Implementar k-NN e regressão logística sem bibliotecas de ML.',
      'Rede com uma camada escondida em NumPy (forward, loss, backprop).',
      'Comparar acurácia, precisão, revocação e matriz de confusão.',
      'Relatório com limitações, vieses possíveis e o que não se pode concluir.',
    ],
    milestones: [
      { title: 'Parte 1: dados e baseline', details: 'Classe majoritária como linha de base.' },
      { title: 'Parte 2: k-NN e logística', details: 'Escolha de k com validação.' },
      { title: 'Parte 3: rede neural', details: 'NumPy, depois PyTorch; compare código e resultado.' },
    ],
    acceptance: [
      'O conjunto de teste é usado uma única vez, no fim.',
      'Os resultados são reprodutíveis (semente fixa, versões anotadas).',
      'O relatório compara com a baseline.',
    ],
    stretch: ['Curva de aprendizado (tamanho do treino × erro).', 'Ficha do modelo (model card).'],
    english: [
      t('linha de base', 'baseline', 'Resultado mínimo de referência, de um método trivial.'),
      t('vazamento de dados', 'data leakage', 'Informação do teste que contamina o treino e infla o resultado.'),
      t('sobreajuste', 'overfitting', 'Modelo que decora o treino e generaliza mal.'),
    ],
  },
  {
    id: 'p8-chat',
    order: 8,
    title: 'Chat em rede com servidor concorrente',
    titleEn: 'Networked chat with a concurrent server',
    tier: 'avancado',
    summary: 'Servidor de chat com sockets TCP que atende vários clientes ao mesmo tempo, com um protocolo de texto definido por você.',
    requires: ['m8-3', 'm9-1'],
    skills: ['redes-tcpip', 'redes-sockets', 'so-concorrencia', 'so-processos'],
    requirements: [
      'Servidor TCP com asyncio (ou threads) atendendo vários clientes.',
      'Protocolo documentado: mensagens delimitadas por linha, comandos /nick, /sala, /sair.',
      'Tratar desconexão abrupta sem derrubar o servidor.',
      'Estado compartilhado (salas e usuários) sem condições de corrida.',
      'Testes de integração que abrem vários clientes de verdade.',
    ],
    milestones: [
      { title: 'Eco', details: 'Servidor que devolve o que recebe; observe com nc/telnet.' },
      { title: 'Broadcast', details: 'Mensagem de um cliente chega a todos da sala.' },
      { title: 'Robustez', details: 'Timeouts, limite de tamanho de mensagem, desconexões.' },
    ],
    acceptance: [
      '50 clientes simultâneos em teste automatizado sem perda de mensagens.',
      'Mensagem maior que o limite é recusada com erro do protocolo, sem travar.',
    ],
    stretch: ['TLS com certificado autoassinado.', 'Cliente web via WebSocket.'],
    english: [
      t('soquete', 'socket', 'Ponto de comunicação entre processos pela rede.'),
      t('condição de corrida', 'race condition', 'Resultado que depende da ordem imprevisível de execução.'),
      t('protocolo', 'protocol', 'Regras de formato e ordem das mensagens.'),
    ],
  },
  {
    id: 'p9-fullstack',
    order: 9,
    title: 'Aplicação full-stack em produção',
    titleEn: 'Full-stack application in production',
    tier: 'capstone',
    summary: 'Front-end, API, banco e deploy com CI/CD e observabilidade, resolvendo um problema real de alguém que você conhece.',
    requires: ['m6-3', 'm7-3', 'm10-3', 'm12-2'],
    skills: ['web-backend', 'web-javascript', 'bd-modelagem', 'eng-testes-ci', 'devops-deploy', 'seg-web'],
    requirements: [
      'Um usuário real (familiar, ONG, comércio local) com um problema concreto e escrito.',
      'Front-end acessível, API autenticada e banco relacional com migrações.',
      'CI/CD: testes, build e deploy automáticos a cada merge na main.',
      'Logs, métricas mínimas e alerta de indisponibilidade.',
      'Documento de decisões de arquitetura (ADRs) com pelo menos 3 decisões.',
    ],
    milestones: [
      { title: 'Descoberta', details: 'Entrevista com o usuário e lista de requisitos priorizada.' },
      { title: 'MVP', details: 'Menor versão útil em produção.' },
      { title: 'Iteração', details: 'Duas rodadas de feedback com o usuário.' },
    ],
    acceptance: [
      'O usuário real usou a aplicação e deu feedback documentado.',
      'Rollback de um deploy ruim em menos de 5 minutos, testado.',
      'README permite que outra pessoa rode tudo localmente com 3 comandos.',
    ],
    stretch: ['Testes end-to-end com Playwright.', 'Orçamento de desempenho na CI.'],
    english: [
      t('produto mínimo viável', 'minimum viable product (MVP)', 'A menor versão que já entrega valor real.'),
      t('registro de decisão de arquitetura', 'architecture decision record (ADR)', 'Documento curto: contexto, decisão, consequências.'),
      t('observabilidade', 'observability', 'Capacidade de entender o sistema por logs, métricas e traces.'),
    ],
  },
  {
    id: 'p10-capstone',
    order: 10,
    title: 'Projeto final: contribuição open source',
    titleEn: 'Capstone: open source contribution',
    tier: 'capstone',
    summary: 'Encontrar, entender e melhorar um projeto open source real, do primeiro issue ao pull request aceito, inteiramente em inglês.',
    requires: ['m10-1', 'm10-3'],
    skills: ['tools-git', 'eng-clean-code', 'eng-testes-ci', 'en-leitura-docs'],
    requirements: [
      'Escolher um projeto ativo com guia de contribuição (CONTRIBUTING.md).',
      'Rodar o projeto e os testes localmente.',
      'Resolver um issue (bom primeiro issue, documentação ou bug) com teste.',
      'Comunicar-se em inglês no issue e no PR, seguindo o código de conduta.',
      'Escrever um relato: o que aprendeu sobre a base de código e sobre o processo.',
    ],
    milestones: [
      { title: 'Escolha', details: 'Três candidatos avaliados por atividade, clareza e acolhimento.' },
      { title: 'Leitura', details: 'Mapa da arquitetura do projeto em uma página.' },
      { title: 'Contribuição', details: 'PR aberto, revisões respondidas.' },
    ],
    acceptance: ['PR aberto com descrição clara em inglês e testes passando na CI do projeto.', 'Relato publicado no seu portfólio.'],
    stretch: ['Segunda contribuição no mesmo projeto, maior que a primeira.', 'Revisar o PR de outra pessoa.'],
    english: [
      t('bom primeiro issue', 'good first issue', 'Etiqueta para tarefas indicadas a quem está começando no projeto.'),
      t('mantenedor', 'maintainer', 'Pessoa responsável por revisar e aceitar contribuições.'),
      t('guia de contribuição', 'contributing guide', 'Documento com as regras para contribuir.'),
    ],
  },
];

export const projectById = new Map(projects.map((p) => [p.id, p]));
