import type { Reference } from './types.ts';

/**
 * Referências usadas na trilha. Cada uma existe e foi conferida (URL testada por
 * `npm run check:links`). A nota diz como a fonte influenciou o currículo: a
 * plataforma não copia cursos, ela usa essas fontes como régua de escopo,
 * sequência e profundidade, e manda o aluno para elas quando quer ir além.
 */
const R = (
  id: string,
  title: string,
  org: string,
  url: string,
  kind: Reference['kind'],
  areas: string[],
  note: string,
): Reference => ({ id, title, org, url, kind, areas, note });

export const references: Reference[] = [
  /* ---------- Currículos de referência ---------- */
  R('cs2023', 'Computer Science Curricula 2023 (CS2023)', 'ACM / IEEE-CS / AAAI', 'https://csed.acm.org/', 'padrao', ['n0', 'n3', 'n4', 'n8', 'n9', 'n10', 'n11', 'n13', 'n14'],
    'Corpo de conhecimento usado como checklist de cobertura: cada área de conhecimento (Knowledge Area) do CS2023 foi mapeada para um nível da trilha.'),
  R('cs50', "CS50's Introduction to Computer Science", 'Harvard University', 'https://cs50.harvard.edu/x/', 'universidade', ['n0', 'n1', 'n6', 'n7'],
    'Inspirou a ideia de começar pelo "como o computador representa as coisas" antes da sintaxe, e de fechar cada bloco com um problema real.'),
  R('mit-6100l', '6.100L Introduction to CS and Programming Using Python', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/6-100l-introduction-to-cs-and-programming-using-python-fall-2022/', 'universidade', ['n1', 'n2'],
    'Referência para a escolha de Python como primeira linguagem e para a ordem: tipos, decisões, laços, funções, coleções, testes e depuração.'),
  R('cs61a', 'CS 61A: Structure and Interpretation of Computer Programs', 'UC Berkeley', 'https://cs61a.org/', 'universidade', ['n1', 'n2', 'n4'],
    'Ênfase em abstração, funções de ordem superior e recursão; inspirou os exercícios de "prever a saída" antes de executar.'),
  R('composing-programs', 'Composing Programs', 'John DeNero (UC Berkeley)', 'https://www.composingprograms.com/', 'livro', ['n2', 'n4'],
    'Texto aberto do CS 61A em Python; usado para a explicação de ambientes, escopo e recursão.'),
  R('sicp', 'Structure and Interpretation of Computer Programs', 'Abelson & Sussman (MIT Press)', 'https://sicp.mitpress.mit.edu/', 'livro', ['n4', 'n5'],
    'Clássico sobre abstração; base da seção avançada de abstração de dados e de procedimentos.'),
  R('htdp', 'How to Design Programs', 'Felleisen, Findler, Flatt, Krishnamurthi', 'https://htdp.org/', 'livro', ['n1', 'n2'],
    'A "receita de projeto" (entender, exemplos, esboço, código, testes) inspirou a etapa de resolução de problemas do Nível 1.'),
  R('waterloo-cs135', 'CS 135: Designing Functional Programs', 'University of Waterloo', 'https://student.cs.uwaterloo.ca/~cs135/', 'universidade', ['n1', 'n2'],
    'Curso introdutório canadense baseado em HtDP; reforçou o uso de exemplos e testes escritos antes do código.'),
  R('cmu-15112', '15-112: Fundamentals of Programming and Computer Science', 'Carnegie Mellon University', 'https://www.cs.cmu.edu/~112/', 'universidade', ['n2'],
    'Referência de ritmo e de quantidade de prática: muitos exercícios curtos, com testes automáticos.'),
  R('nand2tetris', 'Nand to Tetris (The Elements of Computing Systems)', 'Nisan & Schocken', 'https://www.nand2tetris.org/', 'curso', ['n0', 'n8'],
    'Inspirou a visualização das portas lógicas e a narrativa "do transistor ao programa".'),
  R('cmu-15213', '15-213: Introduction to Computer Systems', 'Carnegie Mellon University', 'https://www.cs.cmu.edu/~213/', 'universidade', ['n0', 'n8'],
    'Referência para representação de dados (inteiros, ponto flutuante), hierarquia de memória e processos.'),
  R('missing-semester', 'The Missing Semester of Your CS Education', 'MIT CSAIL', 'https://missing.csail.mit.edu/', 'universidade', ['n0', 'n10', 'n12'],
    'Inspirou ensinar terminal, Git e ferramentas cedo, como parte da formação e não como apêndice.'),
  R('mit-6006', '6.006 Introduction to Algorithms', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', 'universidade', ['n3', 'n4'],
    'Escopo de estruturas e algoritmos (busca, ordenação, hashing, grafos, programação dinâmica) do Nível 3 e 4.'),
  R('stanford-cs161', 'CS161: Design and Analysis of Algorithms', 'Stanford University', 'https://web.stanford.edu/class/cs161/', 'universidade', ['n4'],
    'Profundidade de análise (dividir para conquistar, recorrências) usada nos blocos "Aprofundamento".'),
  R('mit-6042', '6.042J Mathematics for Computer Science', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/', 'universidade', ['n4', 'n14'],
    'Base do Nível 14: lógica, provas, indução, contagem e probabilidade discreta.'),
  R('cmu-15445', '15-445/645 Database Systems', 'Carnegie Mellon University', 'https://15445.courses.cs.cmu.edu/', 'universidade', ['n7'],
    'Referência para índices, transações e como um banco de dados funciona por dentro.'),
  R('stanford-cs144', 'CS144: Introduction to Computer Networking', 'Stanford University', 'https://cs144.github.io/', 'universidade', ['n9'],
    'Escopo de redes: camadas, TCP, confiabilidade e roteamento.'),
  R('stanford-cs255', 'CS255: Introduction to Cryptography', 'Stanford University', 'https://crypto.stanford.edu/~dabo/cs255/', 'universidade', ['n11'],
    'Base do módulo de criptografia aplicada: o que é seguro, o que não é, e por que não inventar cripto própria.'),
  R('stanford-cs229', 'CS229: Machine Learning', 'Stanford University', 'https://cs229.stanford.edu/', 'universidade', ['n13'],
    'Escopo de aprendizado supervisionado, generalização e avaliação.'),
  R('stanford-cs231n', 'CS231n: Deep Learning for Computer Vision', 'Stanford University', 'https://cs231n.stanford.edu/', 'universidade', ['n13'],
    'Explicação de redes neurais, retropropagação e otimização.'),
  R('stanford-cs224n', 'CS224N: Natural Language Processing with Deep Learning', 'Stanford University', 'https://web.stanford.edu/class/cs224n/', 'universidade', ['n13'],
    'Referência para embeddings, transformers e modelos de linguagem.'),
  R('harvard-stat110', 'Stat 110: Probability', 'Harvard University', 'https://stat110.hsites.harvard.edu/', 'universidade', ['n14'],
    'Referência para probabilidade condicional, Bayes e variáveis aleatórias.'),
  R('mit-1806', '18.06 Linear Algebra', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/', 'universidade', ['n14'],
    'Base de vetores, matrizes e transformações lineares para IA.'),

  /* ---------- Livros ---------- */
  R('clrs', 'Introduction to Algorithms (4th ed.)', 'Cormen, Leiserson, Rivest, Stein (MIT Press)', 'https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/', 'livro', ['n3', 'n4'],
    'Referência formal para definições e provas de correção dos algoritmos.'),
  R('sedgewick-algs', 'Algorithms, 4th Edition', 'Sedgewick & Wayne (Princeton University)', 'https://algs4.cs.princeton.edu/', 'livro', ['n3', 'n4'],
    'Abordagem visual e empírica (medir tempo de execução) que inspirou as visualizações de ordenação.'),
  R('kleinberg-tardos', 'Algorithm Design', 'Kleinberg & Tardos (Cornell / Pearson)', 'https://www.pearson.com/en-us/subject-catalog/p/algorithm-design/P200000003259', 'livro', ['n4'],
    'Modelagem de problemas reais como problemas de grafos e algoritmos gulosos.'),
  R('bentley-pearls', 'Programming Pearls (2nd ed.)', 'Jon Bentley (Addison-Wesley)', 'https://www.informit.com/store/programming-pearls-9780201657883', 'livro', ['n4'],
    'Inspirou a discussão sobre a busca binária ser fácil de explicar e difícil de acertar.'),
  R('polya', 'How to Solve It', 'George Pólya (Princeton University Press)', 'https://press.princeton.edu/books/paperback/9780691164076/how-to-solve-it', 'livro', ['n1'],
    'Os quatro passos (entender, planejar, executar, revisar) estruturam a resolução de problemas do Nível 1.'),
  R('ostep', 'Operating Systems: Three Easy Pieces', 'Remzi & Andrea Arpaci-Dusseau (Univ. of Wisconsin)', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 'livro', ['n0', 'n8'],
    'Organização do Nível 8 em virtualização, concorrência e persistência.'),
  R('tanenbaum-so', 'Modern Operating Systems (5th ed.)', 'Tanenbaum & Bos (Pearson)', 'https://www.pearson.com/en-us/subject-catalog/p/modern-operating-systems/P200000003295', 'livro', ['n8'],
    'Referência complementar sobre escalonamento e gerência de memória.'),
  R('kurose-ross', 'Computer Networking: A Top-Down Approach', 'Kurose & Ross (Pearson)', 'https://gaia.cs.umass.edu/kurose_ross/', 'livro', ['n0', 'n9'],
    'A abordagem "de cima para baixo" (começar pela aplicação, descer até o enlace) define a ordem do Nível 9.'),
  R('ddia', 'Designing Data-Intensive Applications', "Martin Kleppmann (O'Reilly)", 'https://dataintensive.net/', 'livro', ['n7', 'n10'],
    'Referência para replicação, particionamento e trade-offs de bancos em escala.'),
  R('gof', 'Design Patterns: Elements of Reusable Object-Oriented Software', 'Gamma, Helm, Johnson, Vlissides (Addison-Wesley)', 'https://www.informit.com/store/design-patterns-elements-of-reusable-object-oriented-9780201633610', 'livro', ['n5'],
    'Catálogo original dos padrões de projeto apresentados no Nível 5.'),
  R('refactoring', 'Refactoring (2nd ed.)', 'Martin Fowler', 'https://martinfowler.com/books/refactoring.html', 'livro', ['n5', 'n10'],
    'Vocabulário de "cheiros de código" (code smells) e refatorações usado nos exercícios de corrigir.'),
  R('pragmatic-programmer', 'The Pragmatic Programmer (20th Anniversary ed.)', 'Thomas & Hunt', 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/', 'livro', ['n10'],
    'Hábitos profissionais: DRY, ortogonalidade, depuração sistemática.'),
  R('swe-at-google', 'Software Engineering at Google', "Winters, Manshreck, Wright (O'Reilly)", 'https://abseil.io/resources/swe-book', 'livro', ['n2', 'n10'],
    'Distinção entre programar e fazer engenharia ao longo do tempo; base do Nível 10.'),
  R('pro-git', 'Pro Git (2nd ed.)', 'Scott Chacon & Ben Straub', 'https://git-scm.com/book/en/v2', 'livro', ['n10'],
    'Modelo mental do Git (snapshots, branches como ponteiros) usado no módulo de Git.'),
  R('linux-command-line', 'The Linux Command Line', 'William Shotts', 'https://linuxcommand.org/tlcl.php', 'livro', ['n0', 'n12'],
    'Sequência de aprendizado do terminal e do shell.'),
  R('goldberg-float', 'What Every Computer Scientist Should Know About Floating-Point Arithmetic', 'David Goldberg (ACM Computing Surveys, 1991)', 'https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html', 'artigo', ['n0', 'n2'],
    'Fundamenta por que 0.1 + 0.2 != 0.3 e como comparar números de ponto flutuante.'),
  R('aima', 'Artificial Intelligence: A Modern Approach (4th ed.)', 'Russell & Norvig', 'https://aima.cs.berkeley.edu/', 'livro', ['n13'],
    'Visão ampla de IA (busca, agentes, aprendizado) além de redes neurais.'),
  R('goodfellow-dl', 'Deep Learning', 'Goodfellow, Bengio, Courville (MIT Press)', 'https://www.deeplearningbook.org/', 'livro', ['n13'],
    'Referência matemática para redes neurais e otimização.'),
  R('mml-book', 'Mathematics for Machine Learning', 'Deisenroth, Faisal, Ong (Cambridge University Press)', 'https://mml-book.github.io/', 'livro', ['n13', 'n14'],
    'Ponte entre álgebra linear, cálculo e probabilidade e o que a IA usa deles.'),
  R('rosen-discrete', 'Discrete Mathematics and Its Applications', 'Kenneth Rosen (McGraw Hill)', 'https://www.mheducation.com/highered/product/discrete-mathematics-and-its-applications-rosen.html', 'livro', ['n14'],
    'Referência de exercícios de lógica, conjuntos, contagem e grafos.'),
  R('google-sre', 'Site Reliability Engineering', 'Google', 'https://sre.google/books/', 'livro', ['n12'],
    'Conceitos de SLO, monitoramento e resposta a incidentes do módulo de observabilidade.'),

  /* ---------- Documentação oficial ---------- */
  R('python-docs', 'Documentação oficial do Python', 'Python Software Foundation', 'https://docs.python.org/3/', 'documentacao', ['n0', 'n2', 'n3', 'n8'],
    'Fonte primária de tudo que se afirma sobre Python na trilha.'),
  R('python-tutorial', 'The Python Tutorial', 'Python Software Foundation', 'https://docs.python.org/3/tutorial/', 'documentacao', ['n1', 'n2'],
    'O aluno é convidado a ler trechos do tutorial oficial em inglês desde o Nível 2.'),
  R('pep8', 'PEP 8 – Style Guide for Python Code', 'Python Software Foundation', 'https://peps.python.org/pep-0008/', 'padrao', ['n2', 'n10'],
    'Convenções de nomes e estilo usadas em todos os exemplos.'),
  R('python-sorting-howto', 'Sorting Techniques (HOWTO)', 'Python Software Foundation', 'https://docs.python.org/3/howto/sorting.html', 'documentacao', ['n4'],
    'Uso de key= e estabilidade da ordenação.'),
  R('python-time-complexity', 'TimeComplexity (Python Wiki)', 'Python Software Foundation', 'https://wiki.python.org/moin/TimeComplexity', 'documentacao', ['n3', 'n4'],
    'Custo real das operações de list, dict e set em CPython.'),
  R('python-packaging', 'Python Packaging User Guide', 'Python Packaging Authority', 'https://packaging.python.org/', 'documentacao', ['n2'],
    'Ambientes virtuais e instalação de pacotes.'),
  R('pytest-docs', 'pytest documentation', 'pytest-dev', 'https://docs.pytest.org/', 'documentacao', ['n2', 'n10'],
    'Estilo de testes com assert simples usado nos exercícios.'),
  R('python-tutor', 'Python Tutor', 'Philip Guo', 'https://pythontutor.com/', 'curso', ['n2'],
    'Pesquisa e ferramenta que mostraram o valor de visualizar a execução passo a passo; nosso rastreador segue a mesma ideia.'),
  R('pyodide', 'Pyodide', 'Pyodide project', 'https://pyodide.org/', 'documentacao', ['n2'],
    'Python (CPython compilado para WebAssembly) que roda os exercícios no navegador.'),
  R('unicode', 'The Unicode Standard', 'Unicode Consortium', 'https://www.unicode.org/standard/standard.html', 'padrao', ['n0'],
    'Base da lição sobre texto, code points e UTF-8.'),
  R('linux-man', 'Linux man-pages project', 'Michael Kerrisk', 'https://man7.org/linux/man-pages/', 'documentacao', ['n0', 'n8', 'n12'],
    'Referência para chamadas de sistema e comandos.'),
  R('mdn', 'MDN Web Docs', 'Mozilla', 'https://developer.mozilla.org/pt-BR/', 'documentacao', ['n6'],
    'Fonte primária de HTML, CSS e JavaScript.'),
  R('mdn-http', 'HTTP (MDN Web Docs)', 'Mozilla', 'https://developer.mozilla.org/en-US/docs/Web/HTTP', 'documentacao', ['n0', 'n6', 'n9'],
    'Métodos, códigos de status e cabeçalhos.'),
  R('javascript-info', 'The Modern JavaScript Tutorial', 'Ilya Kantor', 'https://javascript.info/', 'documentacao', ['n6'],
    'Explicação do event loop e de assincronia.'),
  R('ecmascript', 'ECMAScript Language Specification (ECMA-262)', 'Ecma International (TC39)', 'https://tc39.es/ecma262/', 'padrao', ['n6'],
    'Especificação oficial do JavaScript.'),
  R('w3c-html', 'HTML Living Standard', 'WHATWG', 'https://html.spec.whatwg.org/', 'padrao', ['n6'],
    'Especificação oficial do HTML e da semântica dos elementos.'),
  R('wcag', 'Web Content Accessibility Guidelines (WCAG) 2.2', 'W3C', 'https://www.w3.org/TR/WCAG22/', 'padrao', ['n6'],
    'Critérios de acessibilidade ensinados no Nível 6 e aplicados à própria plataforma.'),
  R('rfc9110', 'RFC 9110: HTTP Semantics', 'IETF', 'https://www.rfc-editor.org/rfc/rfc9110', 'padrao', ['n0', 'n6', 'n9'],
    'Definição oficial de métodos idempotentes e seguros e dos códigos de status.'),
  R('rfc9293', 'RFC 9293: Transmission Control Protocol (TCP)', 'IETF', 'https://www.rfc-editor.org/rfc/rfc9293', 'padrao', ['n9'],
    'Handshake de três vias e estados do TCP.'),
  R('cloudflare-learning', 'Cloudflare Learning Center', 'Cloudflare', 'https://www.cloudflare.com/learning/', 'documentacao', ['n9', 'n11'],
    'Explicações acessíveis de DNS, TLS, CDN e ataques DDoS.'),
  R('postgres-docs', 'PostgreSQL Documentation', 'PostgreSQL Global Development Group', 'https://www.postgresql.org/docs/', 'documentacao', ['n7'],
    'Referência de SQL padrão, índices e níveis de isolamento.'),
  R('sqlite-docs', 'SQLite Documentation', 'SQLite', 'https://www.sqlite.org/docs.html', 'documentacao', ['n7'],
    'O banco usado nos exercícios de SQL que rodam no navegador.'),
  R('github-docs', 'GitHub Docs', 'GitHub', 'https://docs.github.com/pt', 'documentacao', ['n10'],
    'Pull requests, GitHub Actions e boas práticas de repositório.'),
  R('docker-docs', 'Docker Docs', 'Docker', 'https://docs.docker.com/', 'documentacao', ['n12'],
    'Imagens, containers, Dockerfile e boas práticas de build.'),
  R('kubernetes-docs', 'Kubernetes Documentation', 'CNCF', 'https://kubernetes.io/docs/home/', 'documentacao', ['n12'],
    'Conceitos de orquestração apresentados no Aprofundamento.'),
  R('twelve-factor', 'The Twelve-Factor App', 'Adam Wiggins', 'https://12factor.net/', 'artigo', ['n12'],
    'Configuração por variáveis de ambiente, processos sem estado e paridade entre ambientes.'),
  R('aws-well-architected', 'AWS Well-Architected Framework', 'Amazon Web Services', 'https://aws.amazon.com/architecture/well-architected/', 'documentacao', ['n12'],
    'Pilares de confiabilidade, segurança, custo e desempenho para decisões de arquitetura.'),
  R('google-ml-crash', 'Machine Learning Crash Course', 'Google', 'https://developers.google.com/machine-learning/crash-course', 'curso', ['n13'],
    'Sequência prática de regressão, classificação, overfitting e métricas.'),

  /* ---------- Segurança e normas ---------- */
  R('owasp-top10', 'OWASP Top 10', 'OWASP Foundation', 'https://owasp.org/www-project-top-ten/', 'padrao', ['n11'],
    'Lista dos riscos mais críticos em aplicações web, usada no Nível 11.'),
  R('owasp-api', 'OWASP API Security Top 10', 'OWASP Foundation', 'https://owasp.org/API-Security/', 'padrao', ['n6', 'n11'],
    'Riscos específicos de APIs, como autorização quebrada em nível de objeto (BOLA).'),
  R('owasp-cheatsheets', 'OWASP Cheat Sheet Series', 'OWASP Foundation', 'https://cheatsheetseries.owasp.org/', 'documentacao', ['n6', 'n7', 'n11'],
    'Receitas de defesa: senhas, sessões, SQL injection, XSS.'),
  R('nist-800-63b', 'NIST SP 800-63B: Digital Identity Guidelines (Authentication)', 'NIST', 'https://pages.nist.gov/800-63-4/sp800-63b.html', 'padrao', ['n11'],
    'Regras modernas de senha (tamanho mínimo, listas de senhas vazadas, sem troca periódica forçada).'),
  R('nist-ai-rmf', 'AI Risk Management Framework (AI RMF 1.0)', 'NIST', 'https://www.nist.gov/itl/ai-risk-management-framework', 'padrao', ['n13'],
    'Base da seção sobre uso responsável de IA: riscos, viés e transparência.'),
];

export const referenceById = new Map(references.map((r) => [r.id, r]));
